### PR TITLE
Task

### PR DESCRIPTION
**Pull request by DanAbsolon**

### CODE REVIEW

**Comment by west-country** [comment]
line 34.html  `<!-- container-for-image-and-text-in-about  #-->`, maybe outside of class quotes

**Comment by west-country** [comment]
117.html `.container-to-create-margins {
	max-width: 50%;
}` could increase in @media screen but might ruin continuous effect. Flex works amazing with resizing browser.

**Comment by west-country** [comment]
27.html, `html {

  font-size: 10px

}` colon?

**Comment by west-country** [comment]
No other comments. works really well and clear styling.

**Review by robin-hodge — APPROVED** [review]

**Pull request merged**
